### ISSUE TITLE
Doesn't alert me

### ISSUE THREAD

**Issue by killerkalamari** [mihai-chezan/owa_notifications_firefox_extension#10]
I had the Office 365 tab open, and checked that it had owa in the URL. I minimized the browser and then sent myself an email from a different account, which I received, but there was no notification that I could see. Restarted the browser just in case, but same problem. Perhaps I just have an incorrect expectation for this extension. I was hoping for it to work similarly to how the Outlook notification did, where it pops over anything else I'm doing, outside the browser window.

Firefox 45.0.1 on Windows 7
Attached a screenshot of the Office 365 browser window and also tags leading up the the Inbox. 

![inbox](https://cloud.githubusercontent.com/assets/5439104/13962287/7b1c5780-f01d-11e5-8bbf-45165ea9b705.png)

![tags](https://cloud.githubusercontent.com/assets/5439104/13962288/7b24a3ea-f01d-11e5-9132-15bedcbf16f8.png)

Thanks!

**Comment by mihai-chezan** [comment]
Try looking here: https://github.com/mihai-chezan/owa_notifications_firefox_extension/issues/9
I hope it helps.

**Comment by karolisp** [comment]
for me a selector that worked was:
`div[id="MailFolderPane.FavoritesFolders"] ._n_B4 ._n_u4[autoid="_n_V"]`
might be excessive but I'm by no means css guru :)
and since it was needed for me, here's css bit for unseen reminder count:
`button[id="O365_Notifications_ButtonID"] > div[class="o365cs-flexPane-unseenitems"] .o365cs-flexPane-unseenCount`

**Comment by mihai-chezan** [comment]
Thank you for sharing
