### ISSUE TITLE
Office 365

### ISSUE THREAD

**Issue by dev-rke** [mihai-chezan/owa_notifications_firefox_extension#16]
Hi,

thank you very much for this extension.
I like the implementation and that you also provide some default settings. Currently i am using 1.8.0-rc2, the webext works great. It would be great to add also selectors for Office 365 support by default, even when it changes sometimes.

I am using these selectors, but i cannot guarantee, that they will work for others, too.

E-Mail-Count (from favorites): 
```
#MailFolderPane\.FavoritesFolders > div:nth-child(1) .ms-bg-color-neutralLighter span
```

Notification Count:
```
#O365_Notifications_ButtonID .o365cs-flexPane-unseenitems span:nth-child(1)
```

Another topic: might it be possible to change the color in the favicon? 
I liked it very much before when it was in red, it was more obviously.

**Comment by mihai-chezan** [comment]
Thank you for your feedback and css selectors contribution.

Question: what version of Office 365 are you using (is it the enterprise one or the regular free for personal use)?
Question: did you try to use the existing selectors from preferences (OWA 365 personal/enterprise)? Do they work for you?

About the colour, sure I can change it but I do remember some other users mentioning the icon being too "visible" and I thought using blue goes with the general Office 365 theme. Maybe I could make it configurable also. I'll think about it. 

At the moment I'm waiting for Mozilla addon reviewers to accept the 1.8.0 version (I've posted it since 24 May but it seems the review queue is too long and there are not enough reviewers).

**Comment by dev-rke** [comment]
> Question: what version of Office 365 are you using (is it the enterprise one or the regular free for personal use)?

It is an enterprise one.

> Question: did you try to use the existing selectors from preferences (OWA 365 personal/enterprise)? 
Do they work for you?

Yes, i did and they do not match.
I also verified using developer console, the IDs are not existing.

**Comment by mihai-chezan** [comment]
Thank you for the clarification.
I'll try to squeeze them in the 1.8.0 release before is approved by Mozilla. If it won't make it, I will push them with the next release.

**Comment by dev-rke** [comment]
FYI: they got all approved, eben when you update them.
Thank you. :-)

**Comment by mihai-chezan** [comment]
I just noticed that the css selector for unread email contains this "ms-bg-color-neutralLighter" but I'm thinking that this is too "custom". Could you try w/o it, so just:
#MailFolderPane\.FavoritesFolders > div:nth-child(1) span
and tell me if it works?

**Comment by dev-rke** [comment]
Hi,

nope, your approach does not work.
The structure is very complex, i also do not like their structure.

This works on my environment:
```
#MailFolderPane\.FavoritesFolders > div:nth-child(1) .canShowFavoritesAction  > div:nth-child(1)  > div:nth-child(1)   > div:nth-child(2) span
```

**Comment by mihai-chezan** [comment]
Just to clarify: your code is the actual css selector, right? 
I'm asking because of the escape there in the first part. So there is an element with id "MailFolderPane.FavoritesFolders" not id "MailFolderPane" and class "FavoritesFolders". And that is why the css selector is 
```
#MailFolderPane\.FavoritesFolders
```
(with the escape) and not 
```
#MailFolderPane.FavoritesFolders
```

**Comment by dev-rke** [comment]
Your question is pretty good. ;-)
In the id of the tag it is called 
```
id="MailFolderPane.FavoritesFolders"
```
Therefore you need to escape it, otherwise ```FavoritesFolders``` would be interpreted as a class definition, e.g. like
```
id="MailFolderPane" class="FavoritesFolders"
```
The escaping is important in this case. :-)

**Comment by mihai-chezan** [comment]
Thank you for clarifying.
