### ISSUE TITLE
Notification shows as double the number of actual new messages/reminders

### ISSUE THREAD

**Issue by rs-saunders** [mihai-chezan/owa_notifications_firefox_extension#8]
Whenever I get notified of a new email or reminder, the count shows twice what there actually is.

If I have one unread, it notifies I have two unread
If I have five unread it, it notifies I have ten unread
etc..

It also notifies for unread emails in the recycle bin too which would be nice if it didn't but not sure that is actually a bug. I have to make sure emails deleted are set to read as a workaround.

![selection_108](https://cloud.githubusercontent.com/assets/4743056/11499056/521c88be-981b-11e5-85df-51c4f6904fe7.png)

**Comment by mihai-chezan** [comment]
It could be because you have the folders added also into Favourites so they are counted twice.
You could try to manually specify the css selector to be used for counting unread emails.
In your case I think this could work:
[fldrnm='Inbox'] + #spnUC #spnCV, [fldrnm='jira'] + #spnUC #spnCV, [fldrnm='slack'] + #spnUC #spnCV, [fldrnm='support'] + #spnUC #spnCV
You set this css using the Add-ons->Extenstions->Preferences->Custom css selector for unread emails detection.
I can't test this, because I no longer have this OWA version, but I hope it works for you.

**Comment by rs-saunders** [comment]
Hi That trick about using a custom css selector worked. Not specifically the one you mentioned to try but this one below did. that limits it to only the notification counts inside the main folder list (ignoring any notifications in the favorites list)

`#mailtree #spnUC #spnCV`

Thanks
Richard

**Comment by seanjohnite** [comment]
This was happening to me as well. I had two elements (one was hidden, but seemed to be in generally the exact same place), and the only difference was that one had an "autoid" attribute. My final selector is `span[title="Inbox"]._n_u4 ~._n_A4 ._n_x4[autoid]`
